interface GlassAttribute {
  name: string
  detail?: string
  documentation?: string
  optional?: boolean
  completion?: string
  values?: string[]
  type?: 'string' | 'boolean' | 'number' | 'object' | 'array' | 'function'
}

export const glassAttributes: Record<string, GlassAttribute[]> = {
  Args: [],
  Assistant: [
    {
      name: 'name',
      detail: 'name of the assistant',
      documentation: 'The `name` attribute allows you to assign a name to an assistant.',
      type: 'string',
      optional: true,
    },
    {
      name: 'generated',
      detail: 'whether the block was generated by running a Glass file',
      documentation: 'The `generated` attribute is set when this Assistant tag was created by running a Glass file.',
      type: 'boolean',
      optional: true,
    },
    {
      name: 'if',
      detail: 'conditional expression',
      documentation: 'The `if` attribute allows you to conditionally render an Assistant block.',
      optional: true,
    },
  ],
  Block: [
    {
      name: 'role',
      detail: 'system, user, or assistant',
      documentation: 'The `role` attribute allows you to assign a role to a chat block.',
      values: ['system', 'user', 'assistant'],
      type: 'string',
    },
    {
      name: 'content',
      detail: 'content of the chat block',
      documentation: 'The `content` attribute allows you to assign string content to a chat block.',
      type: 'string',
    },
    {
      name: 'if',
      detail: 'conditional expression',
      documentation: 'The `if` attribute allows you to conditionally render a block.',
      optional: true,
    },
  ],
  Chat: [
    {
      name: 'model',
      detail: 'chat model for inference',
      documentation: 'The `model` attribute determines which chat model to inference',
      type: 'string',
      values: ['gpt-3.5-turbo', 'gpt-4'],
    },
  ],
  Code: [],
  Completion: [
    {
      name: 'model',
      detail: 'completion model for inference',
      documentation: 'The `model` attribute determines which completion model to inference',
      type: 'string',
      values: ['text-davinci-003', 'ada', 'babbage'],
    },
  ],
  For: [
    {
      name: 'each',
      detail: 'array to iterate over',
      documentation: 'The `each` attribute defines the array you want to iterate over.',
      type: 'array',
      completion: 'each={}',
    },
    {
      name: 'fragment',
      detail: 'fragment to render for each item',
      documentation: 'The `fragment` attribute defines the fragment you want to render for each item.',
      type: 'function',
      completion: 'fragment={item => <Block role={item.role} content={item.content} />}',
      optional: true,
    },
    {
      name: 'item',
      detail: 'alias for each item in the array',
      documentation: 'The `item` attribute defines the alias for each item in the array.',
      type: 'string',
      completion: 'item="item"',
      optional: true,
    },
  ],
  State: [],
  System: [
    {
      name: 'if',
      detail: 'conditional expression',
      documentation: 'The `if` attribute allows you to conditionally render a System block.',
      optional: true,
    },
  ],
  User: [
    {
      name: 'name',
      detail: 'name of the user',
      documentation: 'The `name` attribute allows you to assign a name to a user.',
      type: 'string',
      optional: true,
    },
    {
      name: 'generated',
      detail: 'whether the block was generated by running a Glass file',
      documentation: 'The `generated` attribute is set when this User tag was created by running a Glass file.',
      type: 'boolean',
      optional: true,
    },
    {
      name: 'if',
      detail: 'conditional expression',
      documentation: 'The `if` attribute allows you to conditionally render a User block.',
      optional: true,
    },
  ],
}
