interface GlassElement {
  name: string
  attributes: GlassAttribute[]
  detail?: string
  documentation?: string
  insertText?: string
}

interface GlassAttribute {
  name: string
  detail?: string
  documentation?: string
  optional?: boolean
  insertText?: string
  values?: string[]
  type?: 'string' | 'boolean' | 'number' | 'object' | 'array' | 'function' | 'enum'
}

interface GlassAttribute {
  name: string
  detail?: string
  documentation?: string
  optional?: boolean
  insertText?: string
  values?: string[]
  type?: 'string' | 'boolean' | 'number' | 'object' | 'array' | 'function' | 'enum'
}

export const glassElements: GlassElement[] = [
  {
    name: 'Args',
    attributes: [],
  },
  {
    name: 'Assistant',
    detail: '(block) chat block with role="assistant"',
    documentation: 'Creates an Assistant chat block with inner content',
    attributes: [
      {
        name: 'name',
        detail: 'name of the assistant',
        documentation: 'The `name` attribute allows you to assign a name to an assistant.',
        type: 'string',
        optional: true,
      },
      {
        name: 'generated',
        detail: 'whether the block was generated by running a Glass file',
        documentation: 'The `generated` attribute is set when this Assistant tag was created by running a Glass file.',
        type: 'boolean',
        optional: true,
      },
      {
        name: 'if',
        detail: 'conditional expression',
        documentation: 'The `if` attribute allows you to conditionally render an Assistant block.',
        optional: true,
      },
    ],
  },
  {
    name: 'Block',
    insertText: 'Block role="$1" content="$2" />',
    documentation: 'Creates a chat block',
    detail: '(block) chat block',
    attributes: [
      {
        name: 'role',
        detail: 'system, user, or assistant',
        documentation: 'The `role` attribute allows you to assign a role to a chat block.',
        values: ['system', 'user', 'assistant'],
        type: 'enum',
      },
      {
        name: 'content',
        detail: 'content of the chat block',
        documentation: 'The `content` attribute allows you to assign string content to a chat block.',
        type: 'string',
      },
      {
        name: 'if',
        detail: 'conditional expression',
        documentation: 'The `if` attribute allows you to conditionally render a block.',
        optional: true,
      },
    ],
  },
  {
    name: 'Chat',
    documentation: 'Creates a Chat model inference',
    detail: '(inference) API request to a Chat model',
    attributes: [
      {
        name: 'model',
        detail: 'chat model for inference',
        documentation: 'The `model` attribute determines which chat model to inference',
        type: 'enum',
        values: [
          'gpt-3.5-turbo',
          'gpt-4',
          'gpt-4-0314',
          'gpt-3.5-turbo-0301',
          'claude-v1',
          'claude-v1-100k',
          'claude-instant-v1',
          'claude-instant-v1-100k',
          'claude-v1.3',
          'claude-v1.3-100k',
          'claude-v1.2',
          'claude-v1.0',
          'claude-instant-v1.1',
          'claude-instant-v1.1-100k',
          'claude-instant-v1.0',
        ],
      },
      {
        name: 'temperature',
        detail: 'temperature for inference',
        documentation: 'The `temperature` attribute determines the temperature for inference',
        type: 'number',
        optional: true,
      },
      {
        name: 'maxTokens',
        detail: 'max tokens for inference',
        documentation: 'The `maxTokens` attribute determines the max tokens for inference',
        type: 'number',
        optional: true,
      },
      {
        name: 'onResponse',
        detail: 'callback for response',
        documentation: 'The `onResponse` attribute allows you to define a callback for the response.',
        type: 'function',
        optional: true,
      },
    ],
  },
  {
    name: 'Code',
    documentation: 'Creates a Code tag with inner content',
    detail: '(executable) executable code block',
    attributes: [],
  },
  {
    name: 'Completion',
    documentation: 'Creates a Completion model inference',
    detail: '(inference) API request to a Completion model',
    attributes: [
      {
        name: 'model',
        detail: 'completion model for inference',
        documentation: 'The `model` attribute determines which completion model to inference',
        type: 'enum',
        values: [
          // openai
          'text-davinci-003',
          'text-curie-001',
          'text-babbage-001',
          'text-ada-001',
          'text-davinci-002',
          'text-davinci-001',
          'davinci-instruct-beta',
          'davinci',
          'curie',
          'babbage',
          'ada',
        ],
      },
    ],
  },
  {
    name: 'For',
    documentation: 'Creates a for loop',
    detail: '(element) loop over elements in an array',
    attributes: [
      {
        name: 'each',
        detail: 'array to iterate over',
        documentation: 'The `each` attribute defines the array you want to iterate over.',
        type: 'array',
      },
      {
        name: 'item',
        detail: 'alias for each item in the array',
        documentation: 'The `item` attribute defines the alias for each item in the array.',
        type: 'string',
      },
    ],
  },
  {
    name: 'State',
    insertText: 'State>\n{\n\t"$1": "$2"\n}\n</State>',
    documentation: 'Creates a State tag to hold document state',
    detail: '(element) holds document state',
    attributes: [],
  },
  {
    name: 'System',
    documentation: 'Creates a System chat block with inner content',
    detail: '(element) raw Glass text block',
    attributes: [
      {
        name: 'if',
        detail: 'conditional expression',
        documentation: 'The `if` attribute allows you to conditionally render a System block.',
        optional: true,
      },
    ],
  },
  {
    name: 'Test',
    documentation: 'Creates a Test tag to hold test cases',
    detail: '(element) holds test cases',
    attributes: [],
  },
  {
    name: 'Text',
    attributes: [
      {
        name: 'if',
        detail: 'conditional expression',
        documentation: 'The `if` attribute allows you to conditionally render text.',
        optional: true,
      },
    ],
  },
  {
    name: 'User',
    insertText: 'User>\n$1\n</User>',
    documentation: 'Creates a User tag with inner content',
    detail: '(block) chat block with role="user"',
    attributes: [
      {
        name: 'name',
        detail: 'name of the user',
        documentation: 'The `name` attribute allows you to assign a name to a user.',
        type: 'string',
        optional: true,
      },
      {
        name: 'generated',
        detail: 'whether the block was generated by running a Glass file',
        documentation: 'The `generated` attribute is set when this User tag was created by running a Glass file.',
        type: 'boolean',
        optional: true,
      },
      {
        name: 'if',
        detail: 'conditional expression',
        documentation: 'The `if` attribute allows you to conditionally render a User block.',
        optional: true,
      },
    ],
  },
]
