// THIS FILE WAS GENERATED BY GLASS -- DO NOT EDIT!

import { interpolateGlass } from '@glass-lang/glasslib'

export function getGpt3Prompt() {
  const interpolations = {}
  const TEMPLATE =
    '<Prompt>\ntell me a funny story about ?\n\nqwecpoijqwefpoij\n\nqwecpoijqwefpoij\n\n##\nqwecpoijqwefpoij\nqwefpoij\n</Prompt>'
  return interpolateGlass('gpt3', TEMPLATE, interpolations)
}

export const Glass = {
  gpt3: getGpt3Prompt,
}
