// THIS FILE WAS GENERATED BY GLASS -- DO NOT EDIT!

import { interpolateGlass } from '@glass-lang/glasslib'

export function getGpt3Prompt(args: { something: string }) {
  const { something } = args

  const interpolations = {
    0: something,
  }
  const TEMPLATE = '<Prompt>\ntell me a funny story about ${0}?\n</Prompt>'
  return interpolateGlass('gpt3', TEMPLATE, interpolations)
}

export const Glass = {
  gpt3: getGpt3Prompt,
}
