// THIS FILE WAS GENERATED BY GLASS -- DO NOT EDIT!

import { interpolateGlass } from '@glass-lang/interpolator'

export function getGpt3Prompt(args: { person: string }) {
  const { person } = args

  const interpolations = {
    0: person,
  }
  const TEMPLATE = '<Prompt>\nwho was ${0}?\n</Prompt>'
  return interpolateGlass('gpt3', TEMPLATE, interpolations)
}

export const Glass = {
  gpt3: getGpt3Prompt,
}
